# Generated by Django 2.0.1 on 2018-01-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineering',
            fields=[
                ('eng_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('instructions', models.CharField(max_length=500, null=True)),
                ('request_date', models.DateField(verbose_name='request date')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('delivery', models.DateField(verbose_name='delivery date')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('project_no', models.IntegerField(primary_key=True, serialize=False)),
                ('r_type', models.CharField(choices=[('ORDER', 'Order'), ('SAMPLE', 'Sample'), ('ECR', 'Ecr'), ('ERF', 'Erf')], default='ORDER', max_length=20)),
                ('description', models.CharField(max_length=255, null=True)),
                ('customer', models.CharField(max_length=50, null=True)),
                ('order_by', models.CharField(max_length=50, null=True)),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
                ('estimate', models.DateField(verbose_name='estimate date')),
                ('status', models.CharField(choices=[('QUEUE', 'Queue'), ('WIP', 'Wip'), ('COMPLETE', 'Complete'), ('HOLD', 'Hold')], default='QUEUE', max_length=20)),
                ('eng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Engineering')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order')),
            ],
        ),
    ]
