# Generated by Django 2.0.1 on 2018-01-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_type', models.CharField(choices=[('BBT', 'bbt'), ('BTY', 'bty'), ('BLS', 'bls'), ('BRS', 'brs'), ('CKS', 'cks'), ('FMI', 'fmi'), ('GRD', 'grd'), ('LID', 'lid'), ('MFT', 'mft'), ('SHR', 'shr'), ('SPN', 'spn'), ('TRL', 'trl')], default='BBT', max_length=20)),
                ('drawing_no', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('technology', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Staff'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Staff'),
        ),
    ]
