# Generated by Django 2.0.1 on 2018-01-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('A', 'Queue'), ('B', 'Wip'), ('C', 'Complete'), ('D', 'Hold')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='type_of_choice',
            field=models.CharField(choices=[('A', 'Order'), ('B', 'Sample')], default='A', max_length=1),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='TypeOfChoice',
        ),
    ]
