# Generated by Django 2.0.1 on 2018-01-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='order_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
