# Generated by Django 2.0.1 on 2018-01-17 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180117_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_type',
            field=models.CharField(choices=[('BBT', 'BBT'), ('BTY', 'BTY'), ('BLS', 'BLS'), ('BRS', 'BRS'), ('CKS', 'CKS'), ('FMI', 'FMI'), ('GRD', 'GRD'), ('LID', 'LID'), ('MFT', 'MFT'), ('SHR', 'SHR'), ('SPN', 'SPN'), ('TRL', 'TRL')], default='BBT', max_length=20),
        ),
    ]
