# Generated by Django 2.0.1 on 2018-01-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_request_order_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='request',
        ),
        migrations.RemoveField(
            model_name='request',
            name='order_type',
        ),
        migrations.AddField(
            model_name='request',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order'),
        ),
    ]
