# Generated by Django 2.0.1 on 2018-01-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180117_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='order_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Staff'),
        ),
    ]
