# Generated by Django 2.0.1 on 2018-01-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180114_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
        migrations.AddField(
            model_name='entry',
            name='order_type',
            field=models.CharField(default='text here', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='orders.Entry'),
        ),
    ]
