# Generated by Django 2.0.1 on 2018-01-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180114_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='order_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Entry'),
        ),
    ]
