# Generated by Django 2.0.1 on 2018-01-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180114_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Entry'),
        ),
    ]
